
<?php
  
// $randtoken;
// $salt = 'Ruby';
// $generate = openssl_random_pseudo_bytes(32,$salt);
// $aes256Key = hash("SHA256", $generate, true);
// $x = bin2hex($aes256Key);
//    define('CSRF','xxxjhsalajfpaioepfnlos');
//    $_COOKIE['csrf'] = CSRF;
// //    echo $_COOKIE['csrf'];
// echo $x;

/*
    Stonegem (algoritma kekerasan mineral) = 
    Menghitung skala ('diamond', 'ruby', 'Topaz', 'lapiz lazuli')

    // mendapat nilai skala kekeran 1-10 :
    tingakt kekerasan dikali skala mors = digunakan salah salt()

    0,23455() 23455 => mebuat suatu chipper text = [ 


        Diamond(7)

        ENCODE 
        
        xxx-xxx / xxx-xxx / xxx-xxx / xxx-xxx / xxx-xxx / xxx-xxx / xxx-xxx
        1           2         3           4       5           6       7

SHIFFTING (random) [

    (1,5,3,2,4,6,7) =>

    (1,5,4,2)   ==> (  ) ==> suatu file hosting yang aman () => terhubung nek internet
    // (kode =>> )


    // store posisi
    / perbaikan encode (1,234567)
    /(

        ['84 /4 = 11 ==> k' , 
        ' ' ,
        ' ' ,
        ]
    )
    public
]   

    ]



*/


//echo "segas"; 

//
?>
